version: '3'
services:
  app:
    container_name: go-docs
    build: ./build
    tty: true 
    volumes:
      - .:/go/src/go_api
  
  db:
    image: "mysql:5.7"
    container_name: go-docs-mysql
    tty: true 
    environment: 
      MYSQL_DATABASE: go_api
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: go_api_user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local
